// quizData.js
// Ce fichier contient uniquement les données du quiz.

export const quizQuestionsBank = [
  // Questions existantes
  {
    theme: "Green IT",
    question: "Quel est le principal objectif du Green IT ?",
    explanation: "Le Green IT, ou numérique éco-responsable, vise à minimiser les impacts négatifs des technologies sur l'environnement, notamment en réduisant la consommation énergétique et les déchets électroniques.",
    options: [
      "Augmenter la consommation d'énergie des équipements informatiques",
      "Réduire l'impact environnemental des technologies de l'information et de la communication",
      "Développer de nouveaux logiciels pour les jeux vidéo",
    ],
    answerIndex: 1,
  },
  {
    theme: "Politique numérique",
    question: "Quand le manifeste de Green IT Global a-t-il été publié ?",
    explanation: "Le manifeste de Green IT Global a été publié le 14 juin 2017, marquant une étape importante dans la formalisation des principes du numérique responsable à l'échelle internationale.",
    options: ["14 juin 2017", "4 avril 2017", "1 janvier 2018"],
    answerIndex: 0,
  },
  {
    theme: "Green IT",
    question: "Qu'est-ce que l'obsolescence programmée ?",
    explanation: "L'obsolescence programmée est une stratégie industrielle qui consiste à limiter volontairement la durée de vie d'un produit pour pousser le consommateur à le remplacer plus rapidement.",
    options: [
      "La conception d'un produit pour qu'il ait une durée de vie illimitée",
      "La réduction volontaire de la durée de vie d'un produit pour augmenter son taux de remplacement",
      "L'amélioration constante des performances d'un produit",
    ],
    answerIndex: 1,
  },
  {
    theme: "Recyclage",
    question: "Pourquoi est-il important de recycler les équipements électroniques ?",
    explanation: "Le recyclage des DEEE (Déchets d'Équipements Électriques et Électroniques) permet de récupérer des métaux précieux et terres rares, tout en évitant la contamination des sols et de l'eau par des substances toxiques comme le mercure ou le plomb.",
    options: [
      "Pour polluer davantage l'environnement",
      "Pour récupérer des matériaux rares et éviter la dispersion de substances toxiques",
      "Pour encourager l'achat de nouveaux appareils uniquement",
    ],
    answerIndex: 1,
  },
  {
    theme: "Développement durable",
    question: "Quel est l'un des piliers du développement durable appliqué au numérique ?",
    explanation: "La sobriété numérique implique de concevoir des services et des équipements moins gourmands en énergie et en ressources, et d'adopter des usages plus modérés pour réduire l'empreinte globale du numérique.",
    options: [
      "L'augmentation des émissions de gaz à effet de serre",
      "La consommation illimitée de ressources",
      "L'efficacité énergétique et la sobriété numérique",
    ],
    answerIndex: 2,
  },
  
  // NOUVELLES QUESTIONS GÉNÉRÉES
  
  // EUROPE
  {
    theme: "Réglementation Europe",
    question: "Quel est l'objectif de recyclage des métaux critiques fixé par le Critical Raw Materials Act (CRMA) de l'UE pour 2030 ?",
    explanation: "Le CRMA fixe des objectifs ambitieux : extraire 10%, affiner 40% et recycler 25% des métaux critiques consommés annuellement par l'UE d'ici 2030.",
    options: ["10%", "40%", "25%"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Europe",
    question: "À partir de quand la directive européenne \"Right-to-Repair\" (droit à la réparation) sera-t-elle mise en application ?",
    explanation: "La directive Droit à la Réparation, qui oblige les vendeurs à proposer une réparation à coût raisonnable, entrera en application en juillet 2026.",
    options: ["Juillet 2024", "Janvier 2025", "Juillet 2026"],
    answerIndex: 2,
  },
  {
    theme: "Énergie Europe",
    question: "Quelle est la distance maximale entre deux bornes de recharge ultra-rapide (350 kW) imposée par le règlement AFIR sur le réseau TEN-T européen ?",
    explanation: "Le règlement AFIR, adopté en avril 2024, impose l'installation de bornes de recharge ultra-rapide tous les 60 km pour garantir la continuité du service pour les véhicules électriques.",
    options: ["60 km", "100 km", "150 km"],
    answerIndex: 0,
  },
  {
    theme: "Fin de Vie Europe",
    question: "Quel est le nouvel objectif de réemploi pour les DEEE légers fixé par la feuille de route 2024 de la directive WEEE ?",
    explanation: "Pour aller au-delà du simple recyclage, la nouvelle feuille de route de la directive WEEE vise à porter le taux de réemploi des équipements légers à 30%.",
    options: ["10%", "30%", "50%"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Europe",
    question: "Quelle substance chimique la directive européenne \"Restriction PFAS\" (mars 2025) cherche-t-elle à bannir des salles blanches ?",
    explanation: "Le projet de restriction vise les PFAS (substances per- et polyfluoroalkylées), des 'polluants éternels' encore utilisés comme solvants dans l'industrie des semi-conducteurs.",
    options: ["Le silicium", "Les solvants fluorés", "Le cuivre"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Europe",
    question: "À partir de quand les batteries devront-elles être amovibles dans les appareils portables selon le règlement européen ?",
    explanation: "Le règlement 2023/1542 sur les batteries impose que celles-ci soient amovibles et remplaçables par l'utilisateur dès février 2027 pour lutter contre l'obsolescence.",
    options: ["Février 2025", "Février 2027", "Février 2030"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Europe",
    question: "Quelle directive européenne a été la première à limiter l'usage du plomb et du mercure dans les équipements électroniques ?",
    explanation: "La directive RoHS (Restriction of Hazardous Substances), adoptée en 2003, a été pionnière en interdisant plusieurs substances dangereuses dans les produits électroniques mis sur le marché européen.",
    options: ["La directive WEEE", "La directive RoHS", "Le règlement REACH"],
    answerIndex: 1,
  },

  // AMÉRIQUE DU NORD
  {
    theme: "Réglementation USA",
    question: "Quel est le pourcentage de minéraux extraits localement requis en 2027 pour qu'une batterie de VE soit éligible au crédit d'impôt de l'Inflation Reduction Act ?",
    explanation: "L'Inflation Reduction Act augmente progressivement le seuil : il passe de 50% en 2024 à 80% en 2027 pour encourager les chaînes d'approvisionnement nord-américaines.",
    options: ["50%", "70%", "80%"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Canada",
    question: "Quel est le montant alloué par le Canada dans sa Stratégie des minéraux critiques pour développer des hubs d'extraction 'net-zéro' ?",
    explanation: "Le Canada a engagé 4 milliards de dollars pour soutenir sa stratégie, visant à développer une filière minière durable et à faible émission de carbone.",
    options: ["1 milliard $", "4 milliards $", "10 milliards $"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation USA",
    question: "Quel programme volontaire a été créé en 1992 aux États-Unis pour promouvoir les produits écoénergétiques ?",
    explanation: "Le programme ENERGY STAR a été lancé par l'EPA en 1992, en commençant par la certification des ordinateurs et moniteurs, et est devenu un label de renommée mondiale.",
    options: ["Green Seal", "EPEAT", "ENERGY STAR"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation USA",
    question: "Quelle est la cible de réduction d'émissions de GES pour les camions lourds fixée par l'EPA pour la période 2027-2032 ?",
    explanation: "La norme 'Phase 3' de l'EPA (Environmental Protection Agency) est ambitieuse, visant une réduction de 50% des émissions de gaz à effet de serre pour les camions de classe 8.",
    options: ["25%", "50%", "75%"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie USA",
    question: "Quel est l'objectif de la stratégie de l'EPA 'Advancing Sustainable Electronics' pour la capacité de recyclage certifié d'ici 2030 ?",
    explanation: "Les États-Unis visent à quadrupler leur capacité nationale de recyclage électronique certifié d'ici 2030 pour mieux gérer les DEEE et réduire les exportations illégales.",
    options: ["La doubler", "La tripler", "La quadrupler"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Canada",
    question: "En 2024, quelle province canadienne a rejoint le programme de Responsabilité Élargie des Producteurs (REP) pour les petits DEEE ?",
    explanation: "La vague de 2024 a vu plusieurs provinces adopter la REP, dont l'Ontario, qui a ajouté les petits appareils et les batteries portables à son programme.",
    options: ["Québec", "Ontario", "Colombie-Britannique"],
    answerIndex: 1,
  },

  // ASIE
  {
    theme: "Réglementation Chine",
    question: "Quelle est la principale contrainte imposée par la Chine en octobre 2024 sur la gestion des terres rares ?",
    explanation: "Pour conserver la valeur ajoutée sur son territoire, la Chine a instauré des quotas d'extraction et interdit l'exportation de concentrés de terres rares sous certaines teneurs.",
    options: ["Augmentation des exportations", "Interdiction d'exporter les concentrés à faible teneur", "Subvention de l'extraction"],
    answerIndex: 1,
  },
  {
    theme: "Énergie Chine",
    question: "Quel est l'objectif de PUE (Power Usage Effectiveness) moyen pour les data centers en Chine d'ici 2025 ?",
    explanation: "Le plan 'Green DC' chinois fixe un objectif strict de PUE moyen inférieur à 1,5 pour l'ensemble de ses data centers d'ici 2025, et même 1,25 pour les plus grands.",
    options: ["PUE < 2.0", "PUE < 1.5", "PUE < 1.0"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Japon",
    question: "Quelle nouvelle exigence la loi japonaise 'Resource Circulation Act' (2024) impose-t-elle aux fabricants de laptops et téléphones ?",
    explanation: "Pour favoriser la réparation et le recyclage, le Japon impose désormais la publication d'un score de démontabilité pour ces appareils.",
    options: ["Un score de performance énergétique", "Un score de démontabilité", "Une taxe sur les plastiques"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Indonésie",
    question: "Quelle mesure l'Indonésie a-t-elle reconduite en 2024 concernant le nickel ?",
    explanation: "L'Indonésie a maintenu son bannissement d'exportation de minerai de nickel brut pour obliger les entreprises à construire des fonderies et à transformer le minerai localement.",
    options: ["Le bannissement de l'export de minerai brut", "Une subvention à l'exportation", "Une taxe sur l'extraction"],
    answerIndex: 0,
  },
  {
    theme: "Fin de Vie Inde",
    question: "Quel est l'objectif de collecte des déchets électroniques fixé par l'Inde pour 2028 selon ses 'E-Waste Rules' ?",
    explanation: "L'Inde a mis en place un système de REP avec des cibles de collecte très ambitieuses, passant de 60% en 2025 à 80% en 2028.",
    options: ["50%", "60%", "80%"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Singapour",
    question: "Quelle est la condition principale pour obtenir une licence de construction pour un nouveau data center à Singapour depuis 2024 ?",
    explanation: "Après la fin de son moratoire, Singapour n'autorise que les projets de data centers les plus performants, exigeant un PUE inférieur ou égal à 1,3 et un approvisionnement 100% renouvelable.",
    options: ["Utiliser le refroidissement par eau", "Avoir un PUE ≤ 1,3 et 100% d'énergies renouvelables", "Être construit sous terre"],
    answerIndex: 1,
  },

  // AMÉRIQUE LATINE
  {
    theme: "Réglementation Chili",
    question: "En plus d'une redevance, quel pouvoir a été accordé au régulateur chilien (SMA) en 2024 pour la gestion du lithium ?",
    explanation: "Le régulateur SMA peut désormais suspendre en 24h les pompages de saumure de lithium en cas de dépassement des seuils hydrogéologiques, une mesure forte pour protéger les écosystèmes.",
    options: ["Subventionner les entreprises", "Suspendre les pompages de saumure", "Nationaliser les mines"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie Brésil",
    question: "Comment le Brésil trace-t-il les flux de déchets électroniques depuis son décret de 2024 ?",
    explanation: "Le décret sur la logistique inverse a mis en place la plateforme 'Recircula Brasil' pour tracer les flux de déchets et s'assurer que les quotas de recyclage sont atteints.",
    options: ["Avec des registres papier", "Via la plateforme 'Recircula Brasil'", "En interdisant la vente d'électronique"],
    answerIndex: 1,
  },
  {
    theme: "Énergie Chili",
    question: "Quel est l'objectif de vente de camions lourds zéro-émission du Chili pour 2045 ?",
    explanation: "Dans le cadre de sa stratégie d'électromobilité, le Chili vise un objectif de 100% des ventes de camions lourds neufs à être zéro-émission d'ici 2045.",
    options: ["50%", "75%", "100%"],
    answerIndex: 2,
  },
  {
    theme: "Fin de Vie Chili",
    question: "Quel est le taux de collecte des équipements électriques et électroniques (EEE) visé par le Chili pour 2030 ?",
    explanation: "La loi chilienne sur la REP (Responsabilité Élargie des Producteurs) instaure un objectif graduel de collecte atteignant 45% des EEE mis sur le marché en 2030.",
    options: ["25%", "45%", "65%"],
    answerIndex: 1,
  },
  
  // AFRIQUE
  {
    theme: "Réglementation RDC",
    question: "Quelle entité est chargée de superviser les zones d'exploitation artisanale (ASM) de cobalt en République Démocratique du Congo à partir de 2025 ?",
    explanation: "Le décret cobalt de 2025 établit des zones d'exploitation encadrées par l'Entreprise générale du cobalt (EGC) pour améliorer la traçabilité et les conditions de travail.",
    options: ["L'Union Africaine", "L'Entreprise générale du cobalt (EGC)", "L'ONU"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie Afrique du Sud",
    question: "Quelle mesure radicale l'Afrique du Sud a-t-elle prise en 2021 concernant les déchets électroniques ?",
    explanation: "Pour forcer la mise en place de filières de traitement, l'Afrique du Sud a banni la mise en décharge de tous les déchets électroniques ('e-waste').",
    options: ["Leur exportation systématique", "Leur bannissement en décharge", "Leur incinération obligatoire"],
    answerIndex: 1,
  },
  {
    theme: "Politique régionale Afrique",
    question: "Quel est le nom du cadre continental de l'Union Africaine pour une exploitation minière plus juste et durable ?",
    explanation: "L'African Mining Vision est un cadre politique visant à ce que les ressources minérales du continent soient exploitées de manière transparente, équitable et optimale pour le développement de l'Afrique.",
    options: ["Le Plan Minier Africain", "La Vision Minière Africaine (African Mining Vision)", "La Charte des Mines d'Afrique"],
    answerIndex: 1,
  },
  {
    theme: "Énergie Afrique",
    question: "Que visent les accords 'corridors verts' signés dans 5 pays d'Afrique de l'Est pour les data centers ?",
    explanation: "Ces accords visent à connecter en priorité les data centers à des fermes solaires et éoliennes, et à leur offrir des tarifs réseau réduits pour encourager une croissance numérique verte.",
    options: ["Une connexion prioritaire aux énergies renouvelables", "Une taxation plus élevée", "Une limitation de leur taille"],
    answerIndex: 0,
  },

  // OCÉANIE
  {
    theme: "Réglementation Australie",
    question: "Que va créer la réforme de la loi EPBC en Australie en 2025 ?",
    explanation: "La réforme de la principale loi environnementale australienne (EPBC Act) va créer une Agence fédérale indépendante pour l'environnement, afin de garantir des décisions plus impartiales et basées sur la science.",
    options: ["Une nouvelle taxe carbone", "Une Agence fédérale indépendante pour l'environnement", "Un marché du plastique"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie Australie",
    question: "Quel est l'objectif de valorisation matière pour les TV et PC du programme australien NTCRS pour 2027 ?",
    explanation: "Le programme national de recyclage des télévisions et ordinateurs (NTCRS) vise à ce que 80% de la matière des appareils collectés soit valorisée d'ici 2027.",
    options: ["60%", "70%", "80%"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Australie",
    question: "Quelle mesure l'Australie prendra-t-elle en juillet 2025 concernant les produits contenant des PFAS ?",
    explanation: "À partir de juillet 2025, l'Australie interdira l'importation et la fabrication de produits contenant des PFOS, PFOA et PFHxS, des polluants éternels dangereux.",
    options: ["Elle les subventionnera", "Elle les interdira", "Elle en recommandera l'usage"],
    answerIndex: 1,
  },
  
  // ORGANISATIONS MONDIALES
  {
    theme: "International",
    question: "Quel standard international, géré par 57 pays, oblige à la divulgation des impacts environnementaux de l'exploitation minière ?",
    explanation: "L'EITI (Initiative pour la Transparence dans les Industries Extractives) Standard 2023 oblige les pays membres à publier les revenus et les impacts environnementaux du secteur minier, avec un contrôle citoyen.",
    options: ["La norme ISO 14001", "L'EITI Standard 2023", "Le guide de l'OCDE"],
    answerIndex: 1,
  },
  {
    theme: "International",
    question: "Que vise la Convention de Minamata concernant l'orpaillage artisanal ?",
    explanation: "La Convention de Minamata est un traité mondial visant à protéger la santé humaine et l'environnement des effets du mercure. Ses révisions de 2024 renforcent les plans pour éliminer l'usage du mercure dans l'orpaillage.",
    options: ["À promouvoir l'usage du mercure", "À éliminer l'usage du mercure", "À taxer l'usage du mercure"],
    answerIndex: 1,
  },
  {
    theme: "International",
    question: "À quoi sert le 'Battery Passport' développé par la Global Battery Alliance ?",
    explanation: "Le 'Battery Passport' est un passeport numérique qui permet la traçabilité complète d'une batterie, incluant son empreinte CO2, l'origine de ses métaux et le respect des droits du travail.",
    options: ["À faciliter le transport aérien des batteries", "À assurer la traçabilité numérique (CO2, origine, droits humains)", "À certifier la capacité de la batterie uniquement"],
    answerIndex: 1,
  },
  {
    theme: "International",
    question: "Quelle convention internationale, signée en 2001, vise à éliminer les polluants organiques persistants (POP) ?",
    explanation: "La Convention de Stockholm est un traité mondial qui cible les polluants organiques persistants (POP), dont certains étaient utilisés dans l'industrie électronique, afin de les éliminer ou d'en restreindre l'usage.",
    options: ["La Convention de Bâle", "La Convention de Stockholm", "Le Protocole de Kyoto"],
    answerIndex: 1,
  },
  {
    theme: "International",
    question: "Quel était l'objectif principal du Protocole de Kyoto, adopté en 1997 ?",
    explanation: "Le Protocole de Kyoto a été le premier accord international à imposer des objectifs juridiquement contraignants de réduction des émissions de gaz à effet de serre aux pays industrialisés.",
    options: ["Protéger la biodiversité marine", "Fixer des objectifs de réduction des émissions de GES", "Interdire les déchets plastiques"],
    answerIndex: 1,
  },
  {
    theme: "International",
    question: "Quel guide de l'OCDE fournit une procédure en 5 étapes pour la diligence raisonnée dans la chaîne d'approvisionnement des minerais ?",
    explanation: "Le Guide de diligence raisonnée de l'OCDE est la référence mondiale pour les entreprises qui cherchent à s'approvisionner en minerais de manière responsable et à éviter de contribuer aux conflits et aux violations des droits humains.",
    options: ["Le Guide sur la fiscalité", "Le Guide de diligence raisonnée", "Le Guide sur la concurrence"],
    answerIndex: 1,
  },

  // ... (ajout de questions supplémentaires pour atteindre le compte)
  
  {
    theme: "Énergie Europe",
    question: "Quel est l'objectif de réduction des émissions de gaz à effet de serre pour le transport maritime fixé par FuelEU Maritime pour 2050 ?",
    explanation: "La réglementation FuelEU Maritime impose une trajectoire de décarbonation très stricte, visant une réduction de 80% de l'intensité des GES des carburants maritimes d'ici 2050.",
    options: ["-40%", "-60%", "-80%"],
    answerIndex: 2,
  },
  {
    theme: "Énergie International",
    question: "Quel est l'indicateur de performance clé utilisé pour mesurer l'efficacité énergétique des data centers ?",
    explanation: "Le PUE (Power Usage Effectiveness) est le ratio entre l'énergie totale consommée par le data center et l'énergie utilisée par les équipements informatiques. Un PUE proche de 1 indique une très haute efficacité.",
    options: ["Watt par heure (W/h)", "Power Usage Effectiveness (PUE)", "Gigaoctet par seconde (Go/s)"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie International",
    question: "Quel est le principe de la Responsabilité Élargie des Producteurs (REP) ?",
    explanation: "Le principe de la REP, ou pollueur-payeur, étend la responsabilité d'un fabricant à l'ensemble du cycle de vie de son produit, y compris sa collecte et son traitement en fin de vie.",
    options: ["Le consommateur est seul responsable", "Le producteur est responsable de la fin de vie du produit", "L'État est seul responsable"],
    answerIndex: 1,
  },
  {
    theme: "Matières Premières Chili",
    question: "Quel pays a annoncé en 2024 la création d'un réseau de salars protégés dans le cadre de sa Stratégie Nationale du Lithium ?",
    explanation: "Le Chili, l'un des plus grands producteurs de lithium au monde, a annoncé la protection de plusieurs de ses déserts de sel (salars) pour préserver la biodiversité face à l'expansion de l'exploitation minière.",
    options: ["Bolivie", "Argentine", "Chili"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation International",
    question: "Quel sommet mondial de 1992 est considéré comme fondateur pour le développement durable ?",
    explanation: "Le Sommet de la Terre de Rio en 1992 a été un événement historique, menant à l'adoption de la Convention sur le climat (CCNUCC) et du programme Action 21.",
    options: ["Le Sommet de Copenhague (2009)", "Le Sommet de la Terre de Rio (1992)", "L'Accord de Paris (2015)"],
    answerIndex: 1,
  },
    {
    theme: "Énergie USA",
    question: "Quelle agence américaine gère le programme de certification ENERGY STAR ?",
    explanation: "Le programme ENERGY STAR est géré par l'Agence de protection de l'environnement des États-Unis (EPA) depuis sa création en 1992.",
    options: ["Le Département de l'Énergie (DOE)", "L'Agence de protection de l'environnement (EPA)", "La NASA"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie Europe",
    question: "Quel droit la directive européenne de 2024 renforce-t-elle pour les consommateurs ?",
    explanation: "La directive 2024/1364, surnommée 'Right-to-Repair', renforce le droit des consommateurs à faire réparer leurs produits plutôt que de les remplacer.",
    options: ["Le droit de rétractation", "Le droit à la réparation", "Le droit à l'oubli"],
    answerIndex: 1,
  },
  {
    theme: "Matières Premières Chine",
    question: "Quel type de matière première est spécifiquement visé par le règlement chinois d'octobre 2024 ?",
    explanation: "Le règlement d'octobre 2024 concerne la gestion des terres rares, des métaux stratégiques pour lesquels la Chine occupe une position dominante sur le marché mondial.",
    options: ["Le pétrole", "Les terres rares", "Le bois"],
    answerIndex: 1,
  },
  {
    theme: "Énergie Brésil",
    question: "Quel programme au Brésil encourage l'efficacité énergétique des équipements IT gérés par l'État ?",
    explanation: "Le programme PROCEL, via son étiquette Selo, impose des classes d'efficacité et finance la modernisation (retro-commissioning) des data centers publics pour réduire leur consommation.",
    options: ["Le programme Bolsa Família", "Le programme RenovaBio", "Le programme PROCEL"],
    answerIndex: 2,
  },
  {
    theme: "Transport Europe",
    question: "Quel est le pourcentage de Carburants d'Aviation Durables (SAF) requis dans les aéroports européens en 2025 ?",
    explanation: "La réglementation ReFuelEU Aviation impose une incorporation progressive de SAF, commençant à 2% en 2025 pour atteindre 70% en 2050.",
    options: ["2%", "5%", "10%"],
    answerIndex: 0,
  },
  {
    theme: "International",
    question: "Quelle organisation a adopté en 2021 une Recommandation sur l'éthique de l'intelligence artificielle incluant des aspects environnementaux ?",
    explanation: "L'UNESCO a été pionnière en adoptant un cadre éthique mondial pour l'IA, qui demande d'évaluer l'impact environnemental direct et indirect des systèmes d'IA tout au long de leur cycle de vie.",
    options: ["L'Organisation Mondiale du Commerce (OMC)", "L'UNESCO", "Le Fonds Monétaire International (FMI)"],
    answerIndex: 1,
  },
    {
    theme: "Réglementation Europe",
    question: "Quelle est la principale mission de l'Agence Européenne pour l'Environnement (AEE), créée en 1990 ?",
    explanation: "La mission de l'AEE est de fournir des informations fiables et indépendantes sur l'état de l'environnement pour aider les décideurs politiques et informer le public.",
    options: ["Financer des projets écologiques", "Fournir des informations indépendantes sur l'environnement", "Juger les crimes environnementaux"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie USA",
    question: "Quel a été le premier État américain à adopter une loi sur le recyclage des déchets électroniques en 2003 ?",
    explanation: "La Californie a été pionnière avec son 'Electronic Waste Recycling Act' de 2003, établissant un programme de financement pour la collecte et le recyclage des DEEE.",
    options: ["New York", "Texas", "Californie"],
    answerIndex: 2,
  },
  {
    theme: "Matières Premières International",
    question: "Quel standard de certification minière volontaire est basé sur plus de 400 critères 'best-in-class' ?",
    explanation: "L'IRMA (Initiative for Responsible Mining Assurance) Standard est l'un des plus exigeants, certifiant les mines site par site sur des centaines de critères sociaux et environnementaux.",
    options: ["ISO 9001", "Fairtrade", "IRMA Standard"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Asie",
    question: "Quelle loi de 2007 en Corée du Sud a introduit un système de REP pour les équipements électroniques ?",
    explanation: "La Corée du Sud a mis en place un système de Responsabilité Élargie des Producteurs (REP) avec sa loi sur le recyclage des ressources, obligeant les fabricants à gérer la fin de vie de leurs produits.",
    options: ["La loi sur la pureté de l'air", "La loi sur le recyclage des ressources", "La loi sur la protection des consommateurs"],
    answerIndex: 1,
  },
  {
    theme: "Transport International",
    question: "La Convention de Bâle régit les mouvements transfrontaliers de quels types de produits ?",
    explanation: "La Convention de Bâle contrôle les mouvements de déchets dangereux. Ses amendements de 2025 renforcent le contrôle sur les déchets électroniques ('e-waste') pour prévenir leur traitement inapproprié dans les pays en développement.",
    options: ["Les denrées alimentaires", "Les déchets dangereux et électroniques", "Les animaux vivants"],
    answerIndex: 1,
  },
  {
    theme: "Énergie International",
    question: "Un PUE de 1.1 signifie qu'un data center est...",
    explanation: "Un PUE de 1.1 signifie que pour chaque watt consommé par les serveurs, seulement 0.1 watt est utilisé pour le refroidissement et l'infrastructure. C'est un excellent score d'efficacité énergétique.",
    options: ["Peu efficace", "Moyennement efficace", "Très efficace"],
    answerIndex: 2,
  },
  {
    theme: "Réglementation Australie",
    question: "Quelle est la principale loi-cadre environnementale fédérale en Australie, adoptée en 1999 ?",
    explanation: "L'Environment Protection and Biodiversity Conservation Act (EPBC Act) de 1999 est la pièce maîtresse de la législation environnementale australienne au niveau fédéral.",
    options: ["Le Clean Energy Act", "L'EPBC Act", "Le Water Act"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie Brésil",
    question: "Quel est le principe clé de la Politique Nationale sur les Déchets Solides du Brésil (2009) ?",
    explanation: "Cette politique a introduit le principe de responsabilité partagée entre les fabricants, les distributeurs, les consommateurs et le gouvernement, ainsi que la logistique inverse pour la gestion des déchets.",
    options: ["L'incinération de tous les déchets", "La responsabilité partagée et la logistique inverse", "La mise en décharge unique"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation France",
    question: "Quel instrument financier la loi 'Industrie Verte' de 2023 en France a-t-elle créé pour décarboner l'industrie ?",
    explanation: "La loi a créé le C3IV (Crédit d'Impôt au titre des Investissements dans l'Industrie Verte) pour soutenir financièrement les entreprises qui investissent dans des filières vertes comme les batteries ou l'hydrogène.",
    options: ["Une taxe carbone supplémentaire", "Le crédit d'impôt 'Industrie Verte' (C3IV)", "Des amendes pour les industries polluantes"],
    answerIndex: 1,
  },
  {
    theme: "Énergie Europe",
    question: "Quel mécanisme l'Europe a-t-elle lancé en 2005 pour créer un marché du carbone ?",
    explanation: "Le système d'échange de quotas d'émission de l'UE (EU ETS), lancé en 2005, a été le premier marché international du carbone, obligeant les grands pollueurs à payer pour leurs émissions.",
    options: ["Une subvention verte", "Le marché du carbone (EU ETS)", "Une taxe sur l'essence"],
    answerIndex: 1,
  },
    {
    theme: "International",
    question: "Le 'Sommet de la Terre' de 1992, un événement clé pour l'environnement, a eu lieu dans quelle ville ?",
    explanation: "Le Sommet de la Terre, qui a mené à l'adoption de la Convention sur le climat, s'est tenu à Rio de Janeiro, au Brésil.",
    options: ["Paris", "Kyoto", "Rio de Janeiro"],
    answerIndex: 2,
  },
  {
    theme: "Matières Premières Europe",
    question: "Quel est l'objectif d'affinage des métaux critiques fixé par le CRMA de l'UE pour 2030 ?",
    explanation: "Le CRMA vise à ce que 40% des métaux critiques consommés annuellement par l'UE soient affinés sur son territoire d'ici 2030 pour réduire sa dépendance.",
    options: ["20%", "40%", "60%"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie International",
    question: "Quel est l'un des principaux métaux toxiques dont la directive RoHS limite l'utilisation ?",
    explanation: "La directive européenne RoHS restreint l'utilisation de plusieurs substances dangereuses, notamment le plomb, le mercure, le cadmium et le chrome hexavalent.",
    options: ["L'aluminium", "Le plomb", "Le fer"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation USA",
    question: "Quelle loi américaine de 1990 a été une étape majeure dans la lutte contre les pluies acides et la pollution de l'air ?",
    explanation: "Les amendements de 1990 au Clean Air Act ont considérablement renforcé la réglementation américaine sur la qualité de l'air, en instaurant notamment un système de permis pour les émissions.",
    options: ["Le Clean Water Act", "Le Clean Air Act", "L'Endangered Species Act"],
    answerIndex: 1,
  },
  {
    theme: "Réglementation Afrique",
    question: "Quel traité de 1991 a établi la Communauté économique africaine, posant les bases de la coopération environnementale ?",
    explanation: "Le Traité d'Abuja, signé en 1991, est le traité fondateur de la Communauté économique africaine, qui a pour objectif l'intégration économique du continent.",
    options: ["Le Traité de Maastricht", "Le Traité d'Abuja", "L'Accord de Cotonou"],
    answerIndex: 1,
  },
  {
    theme: "Transport Canada",
    question: "Quel est l'objectif du 'Green Shipping Corridor Program' canadien ?",
    explanation: "Ce programme vise à décarboner le transport maritime en finançant des projets comme l'alimentation électrique à quai (shore-power) et en donnant la priorité aux navires à faibles émissions dans les ports canadiens.",
    options: ["Construire plus de ports", "Décarboner le transport maritime", "Augmenter la vitesse des navires"],
    answerIndex: 1,
  },
  {
    theme: "Fin de Vie International",
    question: "Qu'est-ce que la 'logistique inverse', un principe clé de la loi brésilienne sur les déchets ?",
    explanation: "La logistique inverse est le processus de planification et de contrôle du flux de produits de la fin de vie (du consommateur au fabricant) pour assurer leur recyclage, leur réemploi ou leur élimination appropriée.",
    options: ["Le transport de marchandises la nuit", "Le processus de retour des produits en fin de vie", "L'optimisation des livraisons"],
    answerIndex: 1,
  }
];